const model = @import("../model.zig");

const codegen_io_prefix = "src/codegen/llvm/stmts/io/";
const implied_helpers_owner = "src/codegen/llvm/stmts/io/implied_helpers.zig";

const runtime_prefix = "src/runtime/col6forge_rt/";
const runtime_args_owner = "src/runtime/col6forge_rt/runtime_args.zig";
const runtime_memory_owner = "src/runtime/col6forge_rt/runtime_memory.zig";
const runtime_stride_owner = "src/runtime/col6forge_rt/runtime_stride.zig";
const runtime_text_owner = "src/runtime/col6forge_rt/runtime_text.zig";
const runtime_facade_prefixes = &.{
    "src/runtime/col6forge_rt/io_binary_v/",
    "src/runtime/col6forge_rt/io_list_read/",
};

const io_list_read_prefix = "src/runtime/col6forge_rt/io_list_read/";
const io_list_read_shared = "src/runtime/col6forge_rt/io_list_read/shared.zig";

pub const file_rules = [_]model.AuditRule{
    .{
        .id = "AR-CALL-041",
        .title = "runtime argument helper aliases must bind to runtime_args",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgCount",
        .call_path = "runtime_args.runtimeArgCount",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-042",
        .title = "runtime argument helper aliases must bind to runtime_args",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgPtrAt",
        .call_path = "runtime_args.runtimeArgPtrAt",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-043",
        .title = "runtime argument helper aliases must bind to runtime_args",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgKindAt",
        .call_path = "runtime_args.runtimeArgKindAt",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-044",
        .title = "runtime argument helper aliases must bind to runtime_args",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgLenAt",
        .call_path = "runtime_args.runtimeArgLenAt",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-045",
        .title = "runtime memory helper aliases must bind to runtime_memory",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedAdd",
        .call_path = "runtime_memory.checkedAdd",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-046",
        .title = "runtime memory helper aliases must bind to runtime_memory",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedMul",
        .call_path = "runtime_memory.checkedMul",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-047",
        .title = "runtime memory helper aliases must bind to runtime_memory",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedMulI64",
        .call_path = "runtime_memory.checkedMulI64",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-048",
        .title = "runtime memory helper aliases must bind to runtime_memory",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetBytes",
        .call_path = "runtime_memory.offsetBytes",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-049",
        .title = "runtime memory helper aliases must bind to runtime_memory",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetConstBytes",
        .call_path = "runtime_memory.offsetConstBytes",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-050",
        .title = "runtime stride helper aliases must bind to runtime_stride",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetIndex",
        .call_path = "runtime_stride.offsetIndex",
        .excluded_exact_paths = &.{runtime_stride_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-051",
        .title = "runtime stride helper aliases must bind to runtime_stride",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "complexOffsetIndex",
        .call_path = "runtime_stride.complexOffsetIndex",
        .excluded_exact_paths = &.{runtime_stride_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-052",
        .title = "runtime text helper aliases must bind to runtime_text",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrlen",
        .call_path = "runtime_text.cstrlen",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-053",
        .title = "runtime text helper aliases must bind to runtime_text",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrnlen",
        .call_path = "runtime_text.cstrnlen",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-054",
        .title = "runtime text helper aliases must bind to runtime_text",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrlenRaw",
        .call_path = "runtime_text.cstrlenRaw",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-055",
        .title = "runtime text helper aliases must bind to runtime_text",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "asCStr",
        .call_path = "runtime_text.asCStr",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-056",
        .title = "runtime text helper aliases must bind to runtime_text",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "asConstCStr",
        .call_path = "runtime_text.asConstCStr",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-057",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgCount",
        .call_path = "shared.runtimeArgCount",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-058",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgPtrAt",
        .call_path = "shared.runtimeArgPtrAt",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-059",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgKindAt",
        .call_path = "shared.runtimeArgKindAt",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-060",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgLenAt",
        .call_path = "shared.runtimeArgLenAt",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-061",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "checkedAdd",
        .call_path = "shared.checkedAdd",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-062",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "checkedMul",
        .call_path = "shared.checkedMul",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-063",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "checkedMulI64",
        .call_path = "shared.checkedMulI64",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-064",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "offsetBytes",
        .call_path = "shared.offsetBytes",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-065",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "offsetIndex",
        .call_path = "shared.offsetIndex",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-066",
        .title = "io_list_read facade aliases must bind to shared",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "complexOffsetIndex",
        .call_path = "shared.complexOffsetIndex",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-067",
        .title = "implied-do helper aliases must bind to implied_helpers",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = codegen_io_prefix },
        .symbol_name = "impliedLoopDim",
        .call_path = "implied_helpers.impliedLoopDim",
        .excluded_exact_paths = &.{implied_helpers_owner},
    },
    .{
        .id = "AR-CALL-068",
        .title = "list-directed implied stride alias must bind to implied_helpers",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = "src/codegen/llvm/stmts/io/list_directed.zig" },
        .symbol_name = "impliedStrideForDim",
        .call_path = "implied_helpers.impliedStrideForSymbolDim",
    },
    .{
        .id = "AR-CALL-069",
        .title = "streaming implied stride alias must bind to implied_helpers",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = "src/codegen/llvm/stmts/io/direct/streaming.zig" },
        .symbol_name = "impliedStrideForDim",
        .call_path = "implied_helpers.impliedStrideForSymbolDim",
    },
    .{
        .id = "AR-CALL-070",
        .title = "special write implied stride alias must bind to implied_helpers",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = "src/codegen/llvm/stmts/io/formatted/special_write.zig" },
        .symbol_name = "impliedStrideForDim",
        .call_path = "implied_helpers.impliedStrideForSymbolDim",
    },
    .{
        .id = "AR-CALL-071",
        .title = "unformatted implied stride alias must bind to implied_helpers",
        .kind = .required_symbol_alias_path,
        .scope = .{ .prefix = "src/codegen/llvm/stmts/io/unformatted.zig" },
        .symbol_name = "impliedStrideForDim",
        .call_path = "implied_helpers.impliedStrideForDims",
    },
};
