const model = @import("../model.zig");

const io_binary_v_prefix = "src/runtime/col6forge_rt/io_binary_v/";
const io_binary_v_shared = "src/runtime/col6forge_rt/io_binary_v/shared.zig";
const codegen_io_prefix = "src/codegen/llvm/stmts/io/";
const implied_helpers_owner = "src/codegen/llvm/stmts/io/implied_helpers.zig";
const runtime_prefix = "src/runtime/col6forge_rt/";
const runtime_args_owner = "src/runtime/col6forge_rt/runtime_args.zig";
const runtime_memory_owner = "src/runtime/col6forge_rt/runtime_memory.zig";
const runtime_stride_owner = "src/runtime/col6forge_rt/runtime_stride.zig";
const runtime_text_owner = "src/runtime/col6forge_rt/runtime_text.zig";
const runtime_facade_prefixes = &.{
    "src/runtime/col6forge_rt/io_binary_v/",
    "src/runtime/col6forge_rt/io_list_read/",
};

pub const file_rules = [_]model.AuditRule{
    .{
        .id = "AR-TXT-002",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "emitWriteFormatted",
    },
    .{
        .id = "AR-TXT-003",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "emitReadFormatted",
    },
    .{
        .id = "AR-TXT-004",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "emitSpecialFormattedWrite",
    },
    .{
        .id = "AR-TXT-005",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "emitWriteDynamicFormat",
    },
    .{
        .id = "AR-TXT-006",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "emitReadDynamicFormat",
    },
    .{
        .id = "AR-TXT-007",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "streamFormatSource",
    },
    .{
        .id = "AR-TXT-008",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "emitWriteFormattedStreamPrepared",
    },
    .{
        .id = "AR-TXT-009",
        .title = "legacy formatted entry call",
        .kind = .forbidden_function_call,
        .symbol_name = "emitReadFormattedStreamPrepared",
    },
    .{
        .id = "AR-CALL-001",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "runtimeArgCount",
        .call_path = "shared.runtimeArgCount",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-002",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "runtimeArgPtrAt",
        .call_path = "shared.runtimeArgPtrAt",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-003",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "runtimeArgKindAt",
        .call_path = "shared.runtimeArgKindAt",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-004",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "runtimeArgLenAt",
        .call_path = "shared.runtimeArgLenAt",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-005",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "checkedAdd",
        .call_path = "shared.checkedAdd",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-006",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "checkedMul",
        .call_path = "shared.checkedMul",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-007",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "checkedMulI64",
        .call_path = "shared.checkedMulI64",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-008",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "offsetBytes",
        .call_path = "shared.offsetBytes",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-009",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "offsetConstBytes",
        .call_path = "shared.offsetConstBytes",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-010",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "offsetIndex",
        .call_path = "shared.offsetIndex",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-011",
        .title = "io_binary_v runtime helper calls must stay behind the shared facade",
        .kind = .required_function_call_path,
        .scope = .{ .prefix = io_binary_v_prefix },
        .symbol_name = "complexOffsetIndex",
        .call_path = "shared.complexOffsetIndex",
        .excluded_exact_paths = &.{io_binary_v_shared},
    },
    .{
        .id = "AR-CALL-012",
        .title = "implied-do helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = codegen_io_prefix },
        .symbol_name = "impliedLoopDim",
        .needle = "implied_helpers.zig",
        .excluded_exact_paths = &.{implied_helpers_owner},
    },
    .{
        .id = "AR-CALL-013",
        .title = "implied-do helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = codegen_io_prefix },
        .symbol_name = "impliedStrideForDim",
        .needle = "implied_helpers.zig",
        .excluded_exact_paths = &.{implied_helpers_owner},
    },
    .{
        .id = "AR-CALL-014",
        .title = "implied-do helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = codegen_io_prefix },
        .symbol_name = "impliedStrideForSymbolDim",
        .needle = "implied_helpers.zig",
        .excluded_exact_paths = &.{implied_helpers_owner},
    },
    .{
        .id = "AR-CALL-015",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgCount",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-016",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgPtrAt",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-017",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgKindAt",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-018",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgLenAt",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-019",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedAdd",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-020",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedMul",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-021",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedMulI64",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-022",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetBytes",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-023",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetConstBytes",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-024",
        .title = "runtime stride helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetIndex",
        .needle = "runtime_stride.zig",
        .excluded_exact_paths = &.{runtime_stride_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-025",
        .title = "runtime stride helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "complexOffsetIndex",
        .needle = "runtime_stride.zig",
        .excluded_exact_paths = &.{runtime_stride_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-026",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrlen",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-027",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrnlen",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-028",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrlenRaw",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-029",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "asCStr",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-030",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "asConstCStr",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
};
