const model = @import("../model.zig");

const codegen_io_prefix = "src/codegen/llvm/stmts/io/";
const implied_helpers_owner = "src/codegen/llvm/stmts/io/implied_helpers.zig";

const runtime_prefix = "src/runtime/col6forge_rt/";
const runtime_args_owner = "src/runtime/col6forge_rt/runtime_args.zig";
const runtime_memory_owner = "src/runtime/col6forge_rt/runtime_memory.zig";
const runtime_stride_owner = "src/runtime/col6forge_rt/runtime_stride.zig";
const runtime_text_owner = "src/runtime/col6forge_rt/runtime_text.zig";
const runtime_facade_prefixes = &.{
    "src/runtime/col6forge_rt/io_binary_v/",
    "src/runtime/col6forge_rt/io_list_read/",
};

const io_list_read_prefix = "src/runtime/col6forge_rt/io_list_read/";
const io_list_read_shared = "src/runtime/col6forge_rt/io_list_read/shared.zig";

pub const file_rules = [_]model.AuditRule{
    .{
        .id = "AR-CALL-012",
        .title = "implied-do helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = codegen_io_prefix },
        .symbol_name = "impliedLoopDim",
        .needle = "implied_helpers.zig",
        .excluded_exact_paths = &.{implied_helpers_owner},
    },
    .{
        .id = "AR-CALL-013",
        .title = "implied-do helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = codegen_io_prefix },
        .symbol_name = "impliedStrideForDim",
        .needle = "implied_helpers.zig",
        .excluded_exact_paths = &.{implied_helpers_owner},
    },
    .{
        .id = "AR-CALL-014",
        .title = "implied-do helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = codegen_io_prefix },
        .symbol_name = "impliedStrideForSymbolDim",
        .needle = "implied_helpers.zig",
        .excluded_exact_paths = &.{implied_helpers_owner},
    },
    .{
        .id = "AR-CALL-015",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgCount",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-016",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgPtrAt",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-017",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgKindAt",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-018",
        .title = "runtime argument helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "runtimeArgLenAt",
        .needle = "runtime_args.zig",
        .excluded_exact_paths = &.{runtime_args_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-019",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedAdd",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-020",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedMul",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-021",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "checkedMulI64",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-022",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetBytes",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-023",
        .title = "runtime memory helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetConstBytes",
        .needle = "runtime_memory.zig",
        .excluded_exact_paths = &.{runtime_memory_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-024",
        .title = "runtime stride helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "offsetIndex",
        .needle = "runtime_stride.zig",
        .excluded_exact_paths = &.{runtime_stride_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-025",
        .title = "runtime stride helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "complexOffsetIndex",
        .needle = "runtime_stride.zig",
        .excluded_exact_paths = &.{runtime_stride_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-026",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrlen",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-027",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrnlen",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-028",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "cstrlenRaw",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-029",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "asCStr",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-030",
        .title = "runtime text helper use must import the shared helper module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = runtime_prefix },
        .symbol_name = "asConstCStr",
        .needle = "runtime_text.zig",
        .excluded_exact_paths = &.{runtime_text_owner},
        .excluded_path_prefixes = runtime_facade_prefixes,
    },
    .{
        .id = "AR-CALL-031",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgCount",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-032",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgPtrAt",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-033",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgKindAt",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-034",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "runtimeArgLenAt",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-035",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "checkedAdd",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-036",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "checkedMul",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-037",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "checkedMulI64",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-038",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "offsetBytes",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-039",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "offsetIndex",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
    .{
        .id = "AR-CALL-040",
        .title = "io_list_read shared helper use must import the shared facade module",
        .kind = .required_import_path_fragment_for_symbol_use,
        .scope = .{ .prefix = io_list_read_prefix },
        .symbol_name = "complexOffsetIndex",
        .needle = "shared.zig",
        .excluded_exact_paths = &.{io_list_read_shared},
    },
};
