const model = @import("../model.zig");

pub const file_rules = [_]model.AuditRule{
    .{
        .id = "AR-OWN-001",
        .title = "StringContext type owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .common },
        .symbol_name = "StringContext",
        .definition_kind = .type_struct,
        .owner_exact_path = "src/common/case_insensitive.zig",
    },
    .{
        .id = "AR-OWN-002",
        .title = "ArrayActualPlan type owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .codegen },
        .symbol_name = "ArrayActualPlan",
        .definition_kind = .type_struct,
        .owner_exact_path = "src/codegen/llvm/codegen/expression/call/shared.zig",
    },
    .{
        .id = "AR-OWN-003",
        .title = "CharacterValuePlan type owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .codegen },
        .symbol_name = "CharacterValuePlan",
        .definition_kind = .type_struct,
        .owner_exact_path = "src/codegen/llvm/codegen/expression/dispatch/shared.zig",
    },
    .{
        .id = "AR-OWN-004",
        .title = "PreparedExecutionFormatPlan type owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .codegen },
        .symbol_name = "PreparedExecutionFormatPlan",
        .definition_kind = .type_union,
        .owner_exact_path = "src/codegen/llvm/stmts/io/formatted/context.zig",
    },
    .{
        .id = "AR-OWN-005",
        .title = "semantic test DiagCapture owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .semantic },
        .symbol_name = "DiagCapture",
        .definition_kind = .type_struct,
        .owner_exact_path = "src/semantic/tests/helpers.zig",
    },
    .{
        .id = "AR-OWN-006",
        .title = "intrinsic assignment compatibility helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .semantic },
        .symbol_name = "intrinsicAssignmentTypeCompatible",
        .definition_kind = .function,
        .owner_exact_path = "src/semantic/analysis/check_statements/mod.zig",
    },
    .{
        .id = "AR-OWN-007",
        .title = "implied-do identifier scan helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .codegen },
        .symbol_name = "exprContainsIdentifier",
        .definition_kind = .function,
        .owner_exact_path = "src/codegen/llvm/stmts/io/implied_helpers.zig",
    },
    .{
        .id = "AR-OWN-008",
        .title = "implied-do dimension helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .codegen },
        .symbol_name = "impliedLoopDim",
        .definition_kind = .function,
        .owner_exact_path = "src/codegen/llvm/stmts/io/implied_helpers.zig",
    },
    .{
        .id = "AR-OWN-009",
        .title = "implied-do symbol stride helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .codegen },
        .symbol_name = "impliedStrideForSymbolDim",
        .definition_kind = .function,
        .owner_exact_path = "src/codegen/llvm/stmts/io/implied_helpers.zig",
    },
    .{
        .id = "AR-OWN-010",
        .title = "implied-do extent stride helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .codegen },
        .symbol_name = "impliedStrideForDims",
        .definition_kind = .function,
        .owner_exact_path = "src/codegen/llvm/stmts/io/implied_helpers.zig",
    },
    .{
        .id = "AR-OWN-011",
        .title = "runtime argument count helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "runtimeArgCount",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_args.zig",
    },
    .{
        .id = "AR-OWN-012",
        .title = "runtime argument pointer helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "runtimeArgPtrAt",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_args.zig",
    },
    .{
        .id = "AR-OWN-013",
        .title = "runtime argument kind helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "runtimeArgKindAt",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_args.zig",
    },
    .{
        .id = "AR-OWN-014",
        .title = "runtime argument length helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "runtimeArgLenAt",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_args.zig",
    },
    .{
        .id = "AR-OWN-015",
        .title = "runtime checked add helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "checkedAdd",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_memory.zig",
    },
    .{
        .id = "AR-OWN-016",
        .title = "runtime checked multiply helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "checkedMul",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_memory.zig",
    },
    .{
        .id = "AR-OWN-017",
        .title = "runtime checked i64 multiply helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "checkedMulI64",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_memory.zig",
    },
    .{
        .id = "AR-OWN-018",
        .title = "runtime mutable byte offset helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "offsetBytes",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_memory.zig",
    },
    .{
        .id = "AR-OWN-019",
        .title = "runtime const byte offset helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "offsetConstBytes",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_memory.zig",
    },
    .{
        .id = "AR-OWN-020",
        .title = "runtime element offset helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "offsetIndex",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_stride.zig",
    },
    .{
        .id = "AR-OWN-021",
        .title = "runtime complex element offset helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "complexOffsetIndex",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_stride.zig",
    },
    .{
        .id = "AR-OWN-022",
        .title = "runtime c string length helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "cstrlen",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_text.zig",
    },
    .{
        .id = "AR-OWN-023",
        .title = "runtime bounded c string length helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "cstrnlen",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_text.zig",
    },
    .{
        .id = "AR-OWN-024",
        .title = "runtime raw c string length helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "cstrlenRaw",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_text.zig",
    },
    .{
        .id = "AR-OWN-025",
        .title = "runtime mutable c string cast helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "asCStr",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_text.zig",
    },
    .{
        .id = "AR-OWN-026",
        .title = "runtime const c string cast helper owner",
        .kind = .owned_symbol_definition,
        .scope = .{ .domain = .runtime },
        .symbol_name = "asConstCStr",
        .definition_kind = .function,
        .owner_exact_path = "src/runtime/col6forge_rt/runtime_text.zig",
    },
};
