const model = @import("../model.zig");

pub const file_rules = [_]model.AuditRule{
    .{
        .id = "AR-TXT-001",
        .title = "source doc dependency",
        .kind = .forbidden_text,
        .needle = "docs/errors.md",
    },
    .{
        .id = "AR-TXT-002",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "emitWriteFormatted(",
    },
    .{
        .id = "AR-TXT-003",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "emitReadFormatted(",
    },
    .{
        .id = "AR-TXT-004",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "emitSpecialFormattedWrite(",
    },
    .{
        .id = "AR-TXT-005",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "emitWriteDynamicFormat(",
    },
    .{
        .id = "AR-TXT-006",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "emitReadDynamicFormat(",
    },
    .{
        .id = "AR-TXT-007",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "streamFormatSource(",
    },
    .{
        .id = "AR-TXT-008",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "emitWriteFormattedStreamPrepared(",
    },
    .{
        .id = "AR-TXT-009",
        .title = "legacy formatted entry",
        .kind = .forbidden_text,
        .needle = "emitReadFormattedStreamPrepared(",
    },
    .{
        .id = "AR-TXT-010",
        .title = "compat mirror read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .semantic },
        .needle = "sym.compat.",
    },
    .{
        .id = "AR-TXT-011",
        .title = "compat mirror read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .semantic },
        .needle = "symbol.compat.",
    },
    .{
        .id = "AR-TXT-012",
        .title = "compat mirror read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .codegen },
        .needle = "sym.compat.",
    },
    .{
        .id = "AR-TXT-013",
        .title = "compat mirror read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .codegen },
        .needle = "symbol.compat.",
    },
    .{
        .id = "AR-TXT-014",
        .title = "legacy symbol field read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .semantic },
        .needle = "sym.type_kind",
    },
    .{
        .id = "AR-TXT-015",
        .title = "legacy symbol field read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .semantic },
        .needle = "sym.char_len",
    },
    .{
        .id = "AR-TXT-016",
        .title = "legacy symbol field read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .semantic },
        .needle = "sym.char_len_kind",
    },
    .{
        .id = "AR-TXT-017",
        .title = "legacy symbol field read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .codegen },
        .needle = "sym.type_kind",
    },
    .{
        .id = "AR-TXT-018",
        .title = "legacy symbol field read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .codegen },
        .needle = "sym.char_len",
    },
    .{
        .id = "AR-TXT-019",
        .title = "legacy symbol field read",
        .kind = .forbidden_text,
        .scope = .{ .domain = .codegen },
        .needle = "sym.char_len_kind",
    },
    .{
        .id = "AR-TXT-020",
        .title = "direct Symbol literal",
        .kind = .forbidden_text,
        .scope = .{ .domain = .semantic },
        .needle = "Symbol{",
    },
    .{
        .id = "AR-TXT-021",
        .title = "direct Symbol literal",
        .kind = .forbidden_text,
        .scope = .{ .domain = .codegen },
        .needle = "Symbol{",
    },
    .{
        .id = "AR-TXT-022",
        .title = "bare error code literal",
        .kind = .bare_error_code_literal,
        .exclude_tests = true,
        .excluded_exact_paths = &.{"src/common/error_catalog.zig"},
    },
};
